# Generated by Django 5.1.1 on 2024-11-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='client',
        ),
        migrations.AlterField(
            model_name='testimony',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimony', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], default=5),
            preserve_default=False,
        ),
    ]
