# Generated by Django 5.1.1 on 2024-12-04 16:01

import projects.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_testimony_client_alter_testimony_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(storage=projects.storages.CustomS3Boto3Storage(), upload_to='project_files/'),
        ),
    ]
