# Generated by Django 5.1.1 on 2024-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Project Manager", "Project Manager"),
                    ("Creative Team", "Creative Team"),
                    ("Client", "Client"),
                ],
                max_length=50,
            ),
        ),
    ]
